#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Listens on port 80.

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
