#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Listens on port 80.

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
