#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains a string

sudo apt update
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo sed -i 's/listen 80 default_server;/listen 80 default_server;\nerror_page 404 \/404.html;\nrewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

sudo service nginx restart
