#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and,
# bad luck from China 4th, bad luck from Itay 17th.

k=1
while [ "$k" -le 20 ]
do
	echo "$k"
	case $k in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
	esac
	(( k++ ))
done
